GET http://localhost:1235/api/scrap
###
GET http://localhost:1235/api/getAllItem
###
POST http://localhost:1235/api/info
Content-Type: application/json

{
    "secretKey": "ThisIsKey",
    "itemName" : "bronze"
}
###
POST http://localhost:1235/api/crafting
Content-Type: application/json

{
    "itemName" : "bronze"
}
###

POST http://localhost:1235/api/can-crafting
Content-Type: application/json

{
    "secretKey": "ThisIsKey",
    "itemName" : "bronze"
}
###
POST http://localhost:1235/api/getItemById
Content-Type: application/json

{
    "secretKey": "ThisIsKey",
    "id" : "637c9a53f8c7e15f1991c2b0"
}
###
POST https://valheim.onrender.com/api/can-crafting
Content-Type: application/json

{
    "secretKey": "ThisIsKey",
    "itemName" : "bronze"
}